stages:
  build_features:
    cmd: python ./src/features/build_features.py
    deps:
    - ./data/raw/
    - ./src/features/build_features.py
  train_model:
    cmd: python ./src/models/train_model.py 
    deps:
    - ./data/processed/
    - ./src/models/train_model.py
    params:
    - train_model.n_estimators
    - train_model.max_depth
    - train_model.seed